### ISSUE TITLE
你好请问这个dockerman跟官方openwrt 的dockerman有啥区别

### ISSUE THREAD

**Issue by suyuan168** [lisaac/luci-app-dockerman#140]
**问题描述**

使用 dockerman 时遇到的问题
你好请问这个dockerman跟官方openwrt 的dockerman有啥区别
我是用官方的dockerman .显示空白。只显示dockerman配置。但是下面啥内容都没有。

**Comment by lisaac** [comment]
官方dockerman基于本仓库早期版本

**Comment by lisaac** [comment]
> **问题描述**
> 
> 显示空白。只显示dockerman配置。但是下面啥内容都没有。

这个症状是docker daemon没有启动导致的

**Comment by suyuan168** [comment]
> daemon

非常感谢您的回答，瞌睡我着了半天没有发现docker相关守护进程。是我安装错了吗。docker -V也有相关内容啊。

**Comment by ni7ht** [comment]
> > daemon
> 
> 非常感谢您的回答，瞌睡我着了半天没有发现docker相关守护进程。是我安装错了吗。docker -V也有相关内容啊。

请问你搞定了嘛？我也遇到这问题了，执行service dockerd start也不行
![start](https://user-images.githubusercontent.com/37174285/159117750-83316420-e6bd-4b7e-9819-820f4be77614.png)

**Comment by oscnet** [comment]
我也遇到这个问题

**Comment by AxisRay** [comment]
如何用新版本替换掉官方源里的dockerman？

**Comment by samlin39** [comment]
我用的官方源，切换到22.03.3版本，make menuconfig勾选了dockerd和dockerman
编译完成的系统，一开始也是菜单栏顶部只有一个docker，没有下拉选项。
然后打开`软件包`管理界面，点击`更新列表`，搜索docker，看到`luci-i18n-dockerman-zh-cn`和`luci-app-dockerman`是可升级状态，点击升级，升级后`luci-app-dockerman`版本是`v0.5.13-20230114`
刷新页面后可以看到docker下拉菜单，概览、容器、镜像~~等等

**Comment by samlin39** [comment]
> **问题描述**
> 
> 使用 dockerman 时遇到的问题 你好请问这个dockerman跟官方openwrt 的dockerman有啥区别 我是用官方的dockerman .显示空白。只显示dockerman配置。但是下面啥内容都没有。

我用的官方源，切换到22.03.3版本，make menuconfig勾选了dockerd和dockerman
编译完成的系统，一开始也是菜单栏顶部只有一个docker，没有下拉选项。
然后打开软件包管理界面，点击更新列表，搜索docker，看到luci-i18n-dockerman-zh-cn和luci-app-dockerman是可升级状态，点击升级，升级后luci-app-dockerman版本是v0.5.13-20230114
刷新页面后可以看到docker下拉菜单，概览、容器、镜像~~等等
![Snipaste_2023-04-02_00-21-19](https://user-images.githubusercontent.com/46712710/229302502-197f7e81-c424-42d1-b273-965e283c34f5.jpg)

**Comment by stokito** [comment]
Related: https://github.com/openwrt/luci/issues/6280

@lisaac the openwrt repository diverged from your. There are some commits that are absent in your version https://github.com/openwrt/luci/commits/master/applications/luci-app-dockerman 
It would be hard to backport and copy changes because the repositories have different file structure. Maybe you can fork the https://github.com/openwrt/luci/ and apply changes from your repository then archive it?
Then you can work on your version and easily grab changes and easily create a PR to the openwrt/luci.

I also wish to contribute and send a PR to you but I'm afraid that it would be hard to move the changes into the official openwrt Luci that is used by my router.

**Comment by lisaac** [comment]
yeah, but it requires a considerable of work, and I'm afraid I don't have that much time...

**Comment by stokito** [comment]
the differences aren't that big. I can fork luci and apply your changes and then transfer the repository to you. After that you will have a repo that would be easy to sync with mainline openwrt luci.

**Comment by lisaac** [comment]
> the differences aren't that big. I can fork luci and apply your changes and then transfer the repository to you. After that you will have a repo that would be easy to sync with mainline openwrt luci.

thanks a lot!
